server:
  port: 8888
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:alanzarate/config-repo.git
          default-label: main
          ignoreLocalSshSettings: true
          privateKey: |
                        -----BEGIN OPENSSH PRIVATE KEY-----
                        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
                        NhAAAAAwEAAQAAAYEAygkA3xl9wOBzbyus3QsCl3LHZBvFVIzb1YJB/hYMNlz4PbxL0K4K
                        fDQ8yTL/DOEYOIWxWgVnafrcKomA4z5I3ksPu68heNvVMaH2b4WeAXSY0dFKmEsc8xM8Oe
                        DZYiUz+tI3womKBabvQHt/GNRAUYH53ZA0smEG/C7y1mv+bCJd95kL/snLjO0ksAN3sNWW
                        ERKVS7aYHxhnAcC+5WvOHGR6X36uI8BPf+glse6HfdXxj3JcXHLmJrqJm2GHgm9p2vGtMC
                        sERmLsiKXhoPn6dIK5bbhhz52xOW3BMhlZeb2MsQEUcsUS9AND28CnjpyMPKhdLF3aA/VL
                        eiulM/uXINiBX3ng/ANyEDUwsCTQ1G5M7h12NqUAQAXsw00SRwTAyr6kqAAKybpQ8qSL8x
                        v1SnRqFZyzg9MkpPUOZAxsIprzBMeDdmkTxe/C891EypssB6sYh0IzawsNZxskB/HwlLM8
                        35CucniExv1Ztf+9IKkVjltM69oSfu+NEovgS2WXAAAFiLSTkx20k5MdAAAAB3NzaC1yc2
                        EAAAGBAMoJAN8ZfcDgc28rrN0LApdyx2QbxVSM29WCQf4WDDZc+D28S9CuCnw0PMky/wzh
                        GDiFsVoFZ2n63CqJgOM+SN5LD7uvIXjb1TGh9m+FngF0mNHRSphLHPMTPDng2WIlM/rSN8
                        KJigWm70B7fxjUQFGB+d2QNLJhBvwu8tZr/mwiXfeZC/7Jy4ztJLADd7DVlhESlUu2mB8Y
                        ZwHAvuVrzhxkel9+riPAT3/oJbHuh33V8Y9yXFxy5ia6iZthh4JvadrxrTArBEZi7Iil4a
                        D5+nSCuW24Yc+dsTltwTIZWXm9jLEBFHLFEvQDQ9vAp46cjDyoXSxd2gP1S3orpTP7lyDY
                        gV954PwDchA1MLAk0NRuTO4ddjalAEAF7MNNEkcEwMq+pKgACsm6UPKki/Mb9Up0ahWcs4
                        PTJKT1DmQMbCKa8wTHg3ZpE8XvwvPdRMqbLAerGIdCM2sLDWcbJAfx8JSzPN+QrnJ4hMb9
                        WbX/vSCpFY5bTOvaEn7vjRKL4EtllwAAAAMBAAEAAAGAGjQYvNbdjIqP7jdH8FNhPqtQWR
                        eQ/GpYiNSgIohRhSuBtuAZJTOtgHZ1+9J1agI31fzhB7/zrbcvnwS+hrqpUMuDeuA4Ayjf
                        +dP71nMKDz5EI9J1TlNPqecwxID5MNWKbFmfice08w63sTFTRrEgtnGZKrdtXkVfVo3wSQ
                        cwtG2wqlBbUexyThDj1UBd4b2R/Rzf6DYCfOX5VizdlXvp+5y8km4nv9NNfFVrriw1vohl
                        ECnQ+NyeJR/EgTahELXKVeQp+tat663D1aY/PGj3X3uMGmijF14PdDWN+dFzY0xE7pBKva
                        vJdOuG0BZF6tFL6q6cIazmFO9yS7zWEu/kQHmToev+Veg5hXqyNwqE8R7uJ+0S9D/mpavJ
                        of0VSFyrIls3ZRMKdX5NMk0dBrSexThWGVhYl9ShGEOWjf6N4pCcywTEVArp8bomcKjOBU
                        CfX5/Hut+uxgEHDagUsY05dFMvZCH5RCWqJp5cJRP8SUyL3ZN+PjiX8bpeGuVLUvbhAAAA
                        wG2M/WhAsukjUt8meR+sgEyJO+XSfXzuPc6ySqZWR6zHom5smhnj/a8drWEIUywp2+D7jk
                        zoiV6y2B076yZeUE4GR4Tb+uMFwNYpDZHG2FrLoAMrIiw+DsGnv9foQMUKbS9UqFXL98rO
                        hQWwZF9Dy25RWidMAMVlPLGjEXOuGHBsRhrR1YHoZ1I4YbzqRaVwDHLmwgi2NDyoYmahXF
                        fC2b0Vfc8JJp6TipVD89A0WtahF4HuWefuzEr7PFVQx8FRHwAAAMEA7P/xQOLXQkCpq2qE
                        ffLl3oKC3UfGJGYuqnG6120uEieL4/UHKsK4UxYsy2cVxFXf58VWcS7Y4KubAH1FCGow09
                        LIVRbh8yDqf7/+1o30eQmEvK5xeAiyTGXs++fuD1mkpmwq7WDMc6Qx+YS48uBzysRVX44x
                        JssFSnFAvgC/IGrqOvvlRSs+KZeFQ9T7WcRJ6Fl2+Gnl119zf+PSLvyEqAeBqTerjKX5RZ
                        O6r2uxmFh8DV+uVvJuzR3V/9u1AHjtAAAAwQDaO3dL52pDwHQnf+KJyHE23JD6jVr52XU9
                        CLqY2kYBjsSZz2p3ZgJsQDkMV3YMjv5faYHX8e7kPFccV7PncWD9NzulUrmWHqldff+Pt/
                        2eI2Nkxv7sD/1POtMmudqv1tsd/KXP/hFieNNrgHY+d1XVP7PNWrVwB34EPMLhCvTlUefp
                        MPQQQWOBehaSDtUBFWOAFQ3H9zbgqDI3t239CsZZ6xt9JK9ZBkcwrpFPGQDkcyO9enr9v9
                        Gk+sz16e2anBMAAAASbGFucGxheUBsYW5wbGF5LXBjAQ==
                        -----END OPENSSH PRIVATE KEY-----            

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


        
encrypt:
  key: MYNAMEISHEISENBERG
